class_name JSONTestUtil extends Object

static var type_names: Dictionary[Variant.Type, String] = {
	TYPE_NIL: "TYPE_NIL",
	TYPE_BOOL: "TYPE_BOOL",
	TYPE_INT: "TYPE_INT",
	TYPE_FLOAT: "TYPE_FLOAT",
	TYPE_STRING: "TYPE_STRING",
	TYPE_VECTOR2: "TYPE_VECTOR2",
	TYPE_VECTOR2I: "TYPE_VECTOR2I",
	TYPE_RECT2: "TYPE_RECT2",
	TYPE_RECT2I: "TYPE_RECT2I",
	TYPE_VECTOR3: "TYPE_VECTOR3",
	TYPE_VECTOR3I: "TYPE_VECTOR3I",
	TYPE_TRANSFORM2D: "TYPE_TRANSFORM2D",
	TYPE_VECTOR4: "TYPE_VECTOR4",
	TYPE_VECTOR4I: "TYPE_VECTOR4I",
	TYPE_PLANE: "TYPE_PLANE",
	TYPE_QUATERNION: "TYPE_QUATERNION",
	TYPE_AABB: "TYPE_AABB",
	TYPE_BASIS: "TYPE_BASIS",
	TYPE_TRANSFORM3D: "TYPE_TRANSFORM3D",
	TYPE_COLOR: "TYPE_COLOR",
	TYPE_STRING_NAME: "TYPE_STRING_NAME",
	TYPE_NODE_PATH: "TYPE_NODE_PATH",
	TYPE_RID: "TYPE_RID",
	TYPE_OBJECT: "TYPE_OBJECT",
	TYPE_CALLABLE: "TYPE_CALLABLE",
	TYPE_SIGNAL: "TYPE_SIGNAL",
	TYPE_DICTIONARY: "TYPE_DICTIONARY",
	TYPE_ARRAY: "TYPE_ARRAY",
	TYPE_PACKED_BYTE_ARRAY: "TYPE_PACKED_BYTE_ARRAY",
	TYPE_PACKED_INT32_ARRAY: "TYPE_PACKED_INT32_ARRAY",
	TYPE_PACKED_INT64_ARRAY: "TYPE_PACKED_INT64_ARRAY",
	TYPE_PACKED_FLOAT32_ARRAY: "TYPE_PACKED_FLOAT32_ARRAY",
	TYPE_PACKED_FLOAT64_ARRAY: "TYPE_PACKED_FLOAT64_ARRAY",
	TYPE_PACKED_STRING_ARRAY: "TYPE_PACKED_STRING_ARRAY",
	TYPE_PACKED_VECTOR2_ARRAY: "TYPE_PACKED_VECTOR2_ARRAY",
	TYPE_PACKED_VECTOR3_ARRAY: "TYPE_PACKED_VECTOR3_ARRAY",
	TYPE_PACKED_VECTOR4_ARRAY: "TYPE_PACKED_VECTOR4_ARRAY",
	TYPE_PACKED_COLOR_ARRAY: "TYPE_PACKED_COLOR_ARRAY"
}


static func get_type_of(variant: Variant) -> String:
	return type_names[typeof(variant)]
